services:
  - type: web
    name: pysearch
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python deploy.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.7
